services:
  - type: web
    name: zahari-medical
    runtime: node
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production